[versions]
agp = "8.12.0"
kotlin = "2.2.20-Beta2"
compose = "1.8.3"
composeMultiplatform = "1.8.2"
compose-material3 = "1.3.2"
androidx-activityCompose = "1.10.1"
binary-compatibility-validator = "0.18.1"
dokka = "2.0.0"
dependency-guard = "0.5.0"
kover = "0.9.1"
ktlint = "13.0.0"
versions = "0.52.0"

[libraries]
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
binaryCompatibilityValidator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "binary-compatibility-validator" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
dependency-guard = { id = "com.dropbox.dependency-guard", version.ref = "dependency-guard" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }

build-logic-root = { id = "dev.sdkforge.buildlogic.root" }
build-logic-library-kmp = { id = "dev.sdkforge.buildlogic.library.kmp" }
build-logic-library-android = { id = "dev.sdkforge.buildlogic.library.android" }
build-logic-library-publishing = { id = "dev.sdkforge.buildlogic.library.publishing" }
